[package]
name = "rustris"
version = "0.2.0"
edition = "2024"
description = "A Tetris game written in Rust."
license = "GPL-3.0"

[dependencies]
crossterm = "0.28"
rand = "0.8"
rodio = { version = "0.20", default-features = false }
